### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by ityonemo** [mpope9/exor_filter#6]
https://github.com/mpope9/exor_filter/blob/ff781392a76eacd485029478ee4ce4025ac9141e/c_src/xor_filter_nif.c#L169

should be filter_resource

**Comment by mpope9** [comment]
Good catch, will address this in the next release.

**Comment by mpope9** [comment]
Fixed in https://github.com/mpope9/exor_filter/releases/tag/v0.4.1!
