### ISSUE TITLE
Don't use lists:foldr if traversal order is not important

### ISSUE THREAD

**Issue by Vagabond** [mpope9/exor_filter#7]
https://github.com/mpope9/exor_filter/blob/991a586194e9a566afa01095a3e5e2aede489c70/src/exor_filter.erl#L222-L225

From the Erlang `lists` man page:

    foldl/3 is tail recursive and is usually preferred to foldr/3.

I'd suggest this be rewritten as:

```erlang
 lists:foldl(
         fun(X, Acc) -> 
            [erlang:phash2(X) | Acc ]
         end, [], PassedList),
```

But a lists:map would be even simpler, since you don't do anything but prepend to the accumulator:

```erlang
lists:map(fun erlang:phash2/1, PassedList)
```

**Comment by mpope9** [comment]
Thanks, will integrate this.

**Comment by mpope9** [comment]
Fixed in https://github.com/mpope9/exor_filter/releases/tag/v0.4.1!
